### PR TITLE
Fix CI and docker build

### PR DESCRIPTION
**Pull request by roidelapluie**
- Fix circleci docker hub / quay namespace
- Run go mod tidy

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
I am configuring the dockerhub repos

**Comment by roidelapluie** [comment]
docker and quay should be ready.

**Comment by rakyll** [comment]
Ah, not every platform has sysconf.SC_CLK_TCK. Will guard it behind linux and darwin for now.

**Comment by roidelapluie** [comment]
Yes, I have noticed it.

**Comment by rakyll** [comment]
Only publishing for linux and darwin also sounds good. We can extend it with Windows in the future.

**Comment by roidelapluie** [comment]
This PR is ready ; build is green.

**Review by rakyll — APPROVED** [review]

**Pull request merged**
